# Generated by Django 5.2.15 on 2026-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesnapshot',
            name='calculation_version',
            field=models.IntegerField(default=1),
        ),
    ]
