# Generated by Django 5.2.15 on 2026-06-14 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_membership_unique_membership_period_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_EXPENSE', 'Duplicate Expense'), ('CONFLICTING_DUPLICATE', 'Conflicting Duplicate'), ('UNKNOWN_MEMBER', 'Unknown Member'), ('MEMBERSHIP_VIOLATION', 'Membership Violation'), ('INVALID_SPLIT', 'Invalid Split'), ('INVALID_CURRENCY', 'Invalid Currency'), ('NEGATIVE_AMOUNT', 'Negative Amount'), ('SETTLEMENT_AS_EXPENSE', 'Settlement as Expense')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importbatch')),
            ],
            options={
                'verbose_name': 'Import Anomaly',
                'verbose_name_plural': 'Import Anomalies',
            },
        ),
        migrations.CreateModel(
            name='ImportResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.CharField(choices=[('IGNORE', 'Ignore'), ('MERGE', 'Merge'), ('MAP_USER', 'Map User'), ('CREATE_USER', 'Create User'), ('CONVERT_TO_SETTLEMENT', 'Convert To Settlement'), ('KEEP_BOTH', 'Keep Both')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='imports.importanomaly')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Resolution',
                'verbose_name_plural': 'Import Resolutions',
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('processing_notes', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
            ],
            options={
                'verbose_name': 'Import Row',
                'verbose_name_plural': 'Import Rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='importanomaly',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importrow'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_batch_row_number'),
        ),
    ]
