# Generated by Django 5.2.15 on 2026-06-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('DUPLICATE_EXPENSE', 'Duplicate Expense'), ('CONFLICTING_DUPLICATE', 'Conflicting Duplicate'), ('UNKNOWN_MEMBER', 'Unknown Member'), ('MEMBERSHIP_VIOLATION', 'Membership Violation'), ('INVALID_SPLIT', 'Invalid Split'), ('INVALID_CURRENCY', 'Invalid Currency'), ('NEGATIVE_AMOUNT', 'Negative Amount'), ('SETTLEMENT_AS_EXPENSE', 'Settlement as Expense'), ('MISSING_HEADERS', 'Missing Headers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importanomaly',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importrow'),
        ),
    ]
