# Generated by Django 5.2.15 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importbatch_total_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanomaly',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
