# Generated by Django 5.2.15 on 2026-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_add_anomaly_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='import_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importresolution',
            name='resolution_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
